version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    hostname: rabmq
    environment:
      - RABBITMQ_DEFAULT_USER=ujere
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./volume/rb:/var/lib/rabbitmq/mnesia/ 
    networks:
        - ujere_net      
  database:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
        - 27017:27017
    volumes:
        - ./volume/mongo:/data/db
    networks:
        - ujere_net  
  # # web:
  #   build: ./web
  #   container_name: 'reactapp'
  #   ports:
  #       - 80:8080
  #   networks:
  #       - ujere_net   
  backend:
    build: ./server
    depends_on:
      - database
      - rabbitmq
    container_name: 'backendapp'
    ports:
        - 80:9000
    networks:
        - ujere_net    
  # worker:
  #   build: ./sheetWorker
  #   depends_on:
  #     - database
  #     - rabbitmq
  #     - backend
  #   container_name: 'sheetworker'
  #   networks:
  #       - ujere_net                         
networks:
  ujere_net:
    driver: bridge          