version: "3.3"
services:
  reverse-proxy:
    image: traefik:v2.4
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=false"
      - "--providers.docker=true"
      - "--log.LEVEL=DEBUG"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=umar.jere@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
      - "8001:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
        - ujere_net   
  rabbitmq:
    restart: always
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    hostname: rabmq
    environment:
      - RABBITMQ_DEFAULT_USER=ujere
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./volume/rb:/var/lib/rabbitmq/mnesia/ 
    networks:
        - ujere_net      
  database:
    image: mongo:latest
    container_name: 'mongodb'
    restart: always
    ports:
        - 27017:27017
    volumes:
        - ./volume/mongo:/data/db
    networks:
        - ujere_net  
  backend:
    restart: always
    build: ./server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-server.rule=Host(`ddld.info`)"
      - "traefik.http.routers.node-server.entrypoints=websecure"
      - "traefik.http.routers.node-server.tls.certresolver=myresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
    depends_on:
      - database
      - rabbitmq
    ports:
      - 9000:9000  
    container_name: 'backendapp'
    networks:
        - ujere_net
  paypoint:
    restart: always
    build: ./paypoint
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-server.rule=Host(`paypoint.ddld.info`)"
      - "traefik.http.routers.node-server.entrypoints=web"
    depends_on:
      - reverse-proxy
    container_name: 'paypoint'
    ports:
      - 5000:5000 
    networks:
        - ujere_net              
  worker:
    restart: always
    build: ./sheetWorker
    depends_on:
      - database
      - rabbitmq
    container_name: 'sheetworker'
    networks:
        - ujere_net                         
networks:
  ujere_net:
    driver: bridge          